# almalinux is exactly same as Redhat image, but completely free. 
FROM almalinux:9
LABEL maintainer="Your Name <Joindevops.com>" \
       Course="Docker for Beginners" \
       Trainer="Siva Kumar" \
       Duration="2 hours" \
       AUTHOR="Siva Kumar, Joindevops.com" \
       Version="1.0" \