ARG version
FROM almalinux:${version:-8}
ARG Course="Docker for Beginners" \
    Trainer="Siva Kumar" \
    Duration="2 hours" \
    AUTHOR="Siva Kumar, Joindevops.com" \
    Version="1.0" \
RUN echo "Trainer is : ${Trainer}"